name: 'Create Multi-Architecture Manifest'
description: 'Creates and pushes multi-platform Docker manifests for amd64 and arm64'
inputs:
  image-tag:
    description: 'Image tag to create manifest for'
    required: true
  ecr-registry:
    description: 'ECR registry URL (e.g., 560285300220.dkr.ecr.us-east-1.amazonaws.com/biscred-api)'
    required: true
  aws-account:
    description: 'AWS account name for assuming role'
    required: false
    default: 'bisnow'
  git-sha:
    description: 'Git SHA to create manifest for (defaults to github.sha)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Assume role for AWS Account
      uses: bisnow/github-actions-assume-role-for-environment@main
      with:
        aws-account: ${{ inputs.aws-account }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create and Push Multi-Platform Manifests
      run: |
        ecr_registry="${{ inputs.ecr-registry }}"
        image_tag="${{ inputs.image-tag }}"
        git_sha="${{ inputs.git-sha }}"
        
        if [ -z "$git_sha" ]; then
          git_sha="${{ github.sha }}"
        fi
        
        # Create multi-platform manifest for the image tag
        echo "Creating multi-platform manifest for $image_tag..."
        docker buildx imagetools create \
          --tag "$ecr_registry:$image_tag" \
          "$ecr_registry:$image_tag-amd64" \
          "$ecr_registry:$image_tag-arm64"
        
        # Create multi-platform manifest for the Git SHA tag (required for tag-release workflow)
        echo "Creating multi-platform manifest for Git SHA: $git_sha..."
        docker buildx imagetools create \
          --tag "$ecr_registry:$git_sha" \
          "$ecr_registry:$git_sha-amd64" \
          "$ecr_registry:$git_sha-arm64"
        
        # Verify both manifests were created successfully
        echo "Verifying image tag manifest was created..."
        docker buildx imagetools inspect "$ecr_registry:$image_tag"
        
        echo "Verifying Git SHA manifest was created..."
        docker buildx imagetools inspect "$ecr_registry:$git_sha"
      shell: bash

